language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
install:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install

services:
    - mysql
    - mongodb

before_script:
    - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover coverage.xml"; else PHPUNIT_FLAGS=""; fi
    - mysql -e 'create database notymo_test_db;'
    - sleep 15
    - mongo notymo_test_db

script:
    - phpunit $PHPUNIT_FLAGS;

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi